name: lint
on: 
  pull_request:
  push:
    branches:
      - main

jobs:
    awesome-lint:
      strategy:
        fail-fast: false
        matrix:
          files:
            - "readme.md"
      runs-on: ubuntu-latest
      steps:
        - name: "checkout repo"
          uses: actions/checkout@v2
          with:
            fetch-depth: 0
        - name: asdf_install
          uses: asdf-vm/actions/install@v1
        - name: "linting: ${{ matrix.files }}"
          run: npx -y awesome-lint --no-remark-lint-awesome-toc ${{ matrix.files }}
    awesome-bot:
      strategy:
        fail-fast: false
        matrix:
          files:
            - "readme.md"
      runs-on: ubuntu-latest
      steps:
        - name: "checkout repo"
          uses: actions/checkout@v2.0.0
          with:
            fetch-depth: 0
        - name: "setup ruby"
          uses: ruby/setup-ruby@v1
          with:
            ruby-version: 3.0.1
            bundler-cache: true
        - name: "install awesome-bot"
          run: gem install awesome_bot
        - name: "linting: ${{ matrix.files }}"
          run: awesome_bot --allow-redirect --white-list https://github.com/jdorfman/awesome-amp-cli,https://example.com,https://github.com/user-attachments/assets/44099391-3976-473d-bcf8-95fd7b980f99,https://www.npmjs.com/package/llm-rules,https://www.npmjs.com/package/@sourcegraph/amp ${{ matrix.files }} 
